# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NPTE' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for NPTE
  pod 'Firebase'
  pod 'Firebase/Messaging'

  target 'NPTE-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'NPTETests' do
    inherit! :search_paths
    # Pods for testing
  end

end
